[package]
name = "typst-tikz"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
#rust-tikz = "0.1.0"
wasm-minimal-protocol = { git = "https://github.com/astrale-sharp/wasm-minimal-protocol" }

rust-tikz = { path = "../rust-tikz" }