[package]
name = "typst_tikz"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
#rust_tikz = "0.1.0"
wasm-minimal-protocol = { git = "https://github.com/astrale-sharp/wasm-minimal-protocol" }

rust_tikz = { path = "../rust_tikz" }